CompanyHouseTest/CompanyHouseTest/Controllers/LoginSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace CompanyHouseTest.Controllers
{
    public class LoginSurfaceController : SurfaceController
    {
        // GET: Login
        public ActionResult Index()
        {
            return PartialView("LoginPartial", new LoginModel());
        }

        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            if (Members.Login(model.Username, model.Password))
                return RedirectToUmbracoPage(1114);

            ModelState.AddModelError("", "Invalid Login");

            return CurrentUmbracoPage();
        }

        public ActionResult Logout()
        {
            Members.Logout();
            return RedirectToUmbracoPage(1114);
        }
    }
}

CompanyHouseTest/CompanyHouseTest/Controllers/TaskCreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompanyHouseTest.Models;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace CompanyHouseTest.Controllers
{
    public class TaskCreateController : RenderMvcController
    {
        public ActionResult TaskCreate(RenderModel model)
        {
            var taskRenderModel = new TaskRenderModel {TaskViewModel = new TaskViewModel()};

            IDataTypeService dataTypeService = Services.DataTypeService;

            // Task Status DropDown
            IDataTypeDefinition dataTypeStatus = dataTypeService.GetDataTypeDefinitionByName("TaskStatusDropdown");
            var preValuesStatus = dataTypeService.GetPreValuesCollectionByDataTypeId(dataTypeStatus.Id);

            var selectListStatus = new List<SelectListItem>();

            foreach (var item in preValuesStatus.PreValuesAsDictionary.Where(x => x.Value.Value != "0"))
            {
                selectListStatus.Add(new SelectListItem()
                    {
                        Disabled = false,
                        Selected = false,
                        Text = item.Value.Value, //"On It"
                        Value = item.Value.Id.ToInvariantString() //"33"
                        //Value = item.Value.Value
                    }
                );
            }

            // Task Priority DropDown
            IDataTypeDefinition dataTypePriority = dataTypeService.GetDataTypeDefinitionByName("TaskPriorityDropdown");
            var preValuesPriority = dataTypeService.GetPreValuesCollectionByDataTypeId(dataTypePriority.Id);

            var selectListPriority = new List<SelectListItem>();

            foreach (var item in preValuesPriority.PreValuesAsDictionary.Where(x => x.Value.Value != "0"))
            {
                selectListPriority.Add(new SelectListItem()
                    {
                        Disabled = false,
                        Selected = false,
                        Text = item.Value.Value,
                        Value = item.Value.Id.ToInvariantString()
                        //Value = item.Value.Value
                    }
                );
            }

            taskRenderModel.TaskViewModel.Statuses = selectListStatus;
            taskRenderModel.TaskViewModel.TaskStatus = "34";
            taskRenderModel.TaskViewModel.Priorities = selectListPriority;
            taskRenderModel.TaskViewModel.TaskDate = DateTime.Now;

            var createTaskPage = CurrentPage;
            ViewBag.CreateTaskPage = createTaskPage;

            return CurrentTemplate(taskRenderModel);
        }
    }
}

CompanyHouseTest/CompanyHouseTest/Controllers/TaskRepositoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using CompanyHouseTest.Extensions;
using CompanyHouseTest.Models;
using PagedList;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace CompanyHouseTest.Controllers
{
    public class TaskRepositoryController : RenderMvcController
    {
        // GET: TaskRepository
        public ActionResult TaskRepository(RenderModel model, string priority, string status, string date, int? page)
        {

            var taskRepository = CurrentPage;

            ViewBag.TaskRepository = taskRepository;

            IEnumerable<TaskViewModel> tasks = taskRepository.Children("task").Select(t => t.AsTaskViewModel()).OrderByDescending(t => t.TaskDate);
            ViewBag.CurrentDate = "Desc";

            switch (priority)
            {
                case "Low":
                    tasks = tasks.Where(t => t.TaskPriority == "Low");
                    ViewBag.CurrentPriority = "Low";
                    break;
                case "Normal":
                    tasks = tasks.Where(t => t.TaskPriority == "Normal");
                    ViewBag.CurrentPriority = "Normal";
                    break;
                case "High":
                    tasks = tasks.Where(t => t.TaskPriority == "High");
                    ViewBag.CurrentPriority = "High";
                    break;
            }

            switch (status)
            {
                case "On It":
                    tasks = tasks.Where(t => t.TaskStatus == "On It");
                    ViewBag.CurrentStatus = "On It";
                    break;
                case "Waiting":
                    tasks = tasks.Where(t => t.TaskStatus == "Waiting");
                    ViewBag.CurrentStatus = "Waiting";
                    break;
                case "Finished":
                    tasks = tasks.Where(t => t.TaskStatus == "Finished");
                    ViewBag.CurrentStatus = "Finished";
                    break;
            }

            switch (date)
            {
                case "Asc":
                    tasks = tasks.OrderBy(t => t.TaskDate);
                    ViewBag.CurrentDate = "Asc";
                    break;
                case "Desc":
                    tasks = tasks.OrderByDescending(t => t.TaskDate);
                    ViewBag.CurrentDate = "Desc";
                    break;
            }

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var taskRenderModel = new TaskRenderModel();

            taskRenderModel.TasksPaged = tasks.ToPagedList(pageNumber, pageSize);

     
            return CurrentTemplate(taskRenderModel);
        }
    }
}

CompanyHouseTest/CompanyHouseTest/Controllers/TaskUpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompanyHouseTest.Models;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace CompanyHouseTest.Controllers
{
    public class TaskUpdateController : RenderMvcController
    {
        public ActionResult TaskUpdate(RenderModel model, int? id)
        {
            if (!id.HasValue)
                return Content("No task found");

            var taskRenderModel = new TaskRenderModel();

            IContent taskById = Services.ContentService.GetById(id ?? 0);

            if (taskById == null)
            {
                return HttpNotFound();
            }

            var taskViewModel = new TaskViewModel();
            taskViewModel.ContentId = taskById.Id;
            taskViewModel.FullName = taskById.GetValue<String>("fullName");
            taskViewModel.PhoneNumber = taskById.GetValue<String>("phoneNumber");
            taskViewModel.TaskName = taskById.GetValue<String>("taskName");
            taskViewModel.TaskDescription = taskById.GetValue<String>("taskDescription");
            taskViewModel.LocationInBuilding = taskById.GetValue<String>("locationInBuilding");
            taskViewModel.TaskStatus = taskById.GetValue<string>("taskStatus");
            taskViewModel.TaskPriority = taskById.GetValue<string>("taskPriority");
            taskViewModel.TaskDate = taskById.GetValue<DateTime>("taskDate"); //{2/28/2019 12:00:00 AM}

            taskRenderModel.TaskViewModel = taskViewModel;

            IDataTypeService dataTypeService = Services.DataTypeService;

            // Task Status DropDown
            IDataTypeDefinition dataTypeStatus = dataTypeService.GetDataTypeDefinitionByName("TaskStatusDropdown");
            var preValuesStatus = dataTypeService.GetPreValuesCollectionByDataTypeId(dataTypeStatus.Id);

            var selectListStatus = new List<SelectListItem>();

            foreach (var item in preValuesStatus.PreValuesAsDictionary.Where(x => x.Value.Value != "0"))
            {
                selectListStatus.Add(new SelectListItem()
                    {
                        Disabled = false,
                        Selected = false,
                        Text = item.Value.Value,
                        Value = item.Value.Id.ToInvariantString()
                    }
                );
            }

            // Task Priority DropDown
            IDataTypeDefinition dataTypePriority = dataTypeService.GetDataTypeDefinitionByName("TaskPriorityDropdown");
            var preValuesPriority = dataTypeService.GetPreValuesCollectionByDataTypeId(dataTypePriority.Id);

            var selectListPriority = new List<SelectListItem>();

            foreach (var item in preValuesPriority.PreValuesAsDictionary.Where(x => x.Value.Value != "0"))
            {
                selectListPriority.Add(new SelectListItem()
                    {
                        Disabled = false,
                        Selected = false,
                        Text = item.Value.Value,
                        Value = item.Value.Id.ToInvariantString()
                    }
                );
            }

            taskRenderModel.TaskViewModel.Statuses = selectListStatus;
            taskRenderModel.TaskViewModel.Priorities = selectListPriority;

            var updateTaskPage = CurrentPage;
            ViewBag.UpdateTaskPage = updateTaskPage;

            return CurrentTemplate(taskRenderModel);
        }
    }
}

CompanyHouseTest/CompanyHouseTest/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "_MasterView.cshtml";
}

@Umbraco.Field("homeTitle")

@Umbraco.Field("homeBody")

CompanyHouseTest/CompanyHouseTest/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@using Umbraco.Web
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@{
    Layout = "_MasterView.cshtml";
}

@* the fun starts here *@

<div class="card">
    <div class="card-content">
        <h2 class="title is-2">Caretaker Login:</h2>
        @if (!Members.GetCurrentLoginStatus().IsLoggedIn)
        {
            @Html.Action("Index", "LoginSurface")
        }
        else
        {
            @Html.Partial("Logout")
        }
    </div>
</div>

CompanyHouseTest/CompanyHouseTest/Views/TaskCreate.cshtml
@using CompanyHouseTest.Extensions
@using CompanyHouseTest.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<CompanyHouseTest.Models.TaskRenderModel>
@{
    Layout = "_MasterView.cshtml";

    var taskRepositoryPage = ((IPublishedContent)ViewBag.CreateTaskPage).Siblings().First(x => x.DocumentTypeAlias.Equals("taskRepository"));
    var taskRepositoryPageUrl = taskRepositoryPage.Url;
}


@using (Html.BeginUmbracoForm("CreateTask", "TaskSurface", new object { }, new { @class = "col s12" }))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="card-content">
            <h2 class="title is-2">Create a Task:</h2>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.FullName, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.FullName, new { @class = "input", placeholder = "Caretaker Name" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.FullName)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.PhoneNumber, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.PhoneNumber, new { @class = "input", placeholder = "8 digits" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.PhoneNumber)</span>
            </div>


            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.TaskName, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.TaskName, new { @class = "input", placeholder = "Task Name" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.TaskName)</span>
            </div>


            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.TaskDescription, new { @class = "label" })
                <div class="control">
                    @Html.TextAreaFor(m => m.TaskViewModel.TaskDescription, new { @class = "textarea", placeholder = "Task Description" })
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.TaskDescription)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.LocationInBuilding, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.LocationInBuilding, new { @class = "input", placeholder = "Location In building" })
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.LocationInBuilding)</span>
            </div>

            @*<div class="field">
                    @Html.LabelFor(m => m.TaskViewModel.Statuses, new { @class = "label" })
                    <div class="control">
                        <div class="select">
                            @Html.DropDownListFor(m => m.TaskViewModel.TaskStatus, Model.TaskViewModel.Statuses.ToList(), "Select Status")
                        </div>
                    </div>
                    @Html.ValidationMessageFor(m => m.TaskViewModel.Statuses)
                </div>*@

            @Html.HiddenFor(m => m.TaskViewModel.TaskStatus)

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.Priorities, new { @class = "label" })
                <div class="control">
                    <div class="select">
                        @Html.DropDownListFor(m => m.TaskViewModel.TaskPriority, Model.TaskViewModel.Priorities.ToList(), "Select Priority")
                    </div>
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.Priorities)</span>
            </div>

            @Html.HiddenFor(m => m.TaskViewModel.TaskDate)

            <!-- Form actions -->
            <div class="field is-grouped">
                <p class="control">
                    <input type="submit" name="Submit" value="Create" class="button is-primary" />
                </p>
                <p class="control">
                    <a class="button" href="@taskRepositoryPageUrl">
                        Cancel
                    </a>
                </p>
            </div>
        </div>
    </div>
}

CompanyHouseTest/CompanyHouseTest/Views/TaskUpdate.cshtml
@using CompanyHouseTest.Extensions
@using CompanyHouseTest.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<CompanyHouseTest.Models.TaskRenderModel>
@{
    Layout = "_MasterView.cshtml";

    var taskRepositoryPage = ((IPublishedContent)ViewBag.UpdateTaskPage).Siblings().First(x => x.DocumentTypeAlias.Equals("taskRepository"));
    var taskRepositoryPageUrl = taskRepositoryPage.Url;
}


@using (Html.BeginUmbracoForm("UpdateTask", "TaskSurface", new object {}, new {@class = "col s12"}))
{
    <div class="card">
        <div class="card-content">
            <h2 class="title is-2">Update Task</h2>
            @Html.HiddenFor(m => m.TaskViewModel.ContentId)

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.FullName, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.FullName, new { @class = "input", placeholder = "Caretaker name" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.FullName)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.PhoneNumber, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.PhoneNumber, new { @class = "input", placeholder = "Caretaker name" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.PhoneNumber)</span>
            </div>


            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.TaskName, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.TaskName, new { @class = "input", placeholder = "Task Name" })
                </div>

                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.TaskName)</span>
            </div>


            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.TaskDescription, new { @class = "label" })
                <div class="control">
                    @Html.TextAreaFor(m => m.TaskViewModel.TaskDescription, new { @class = "input", placeholder = "Task Description" })
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.TaskDescription)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.LocationInBuilding, new { @class = "label" })
                <div class="control">
                    @Html.TextBoxFor(m => m.TaskViewModel.LocationInBuilding, new { @class = "input", placeholder = "Location in building" })
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.LocationInBuilding)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.Statuses, new { @class = "label" })
                <div class="control">
                    <div class="select">
                        @Html.DropDownListFor(m => m.TaskViewModel.TaskStatus, Model.TaskViewModel.Statuses.ToList(), Umbraco.DataTypeService.GetPreValueAsString(Int32.Parse(Model.TaskViewModel.TaskStatus)))
                    </div>
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.Statuses)</span>
            </div>

            <div class="field">
                @Html.LabelFor(m => m.TaskViewModel.TaskPriority, new { @class = "label" })
                <div class="control">
                    <div class="select">
                        @Html.DropDownListFor(m => m.TaskViewModel.TaskPriority, Model.TaskViewModel.Priorities.ToList(), Umbraco.DataTypeService.GetPreValueAsString(Int32.Parse(Model.TaskViewModel.TaskPriority)))
                    </div>
                </div>
                <span class="has-text-danger">@Html.ValidationMessageFor(m => m.TaskViewModel.TaskPriority)</span>
            </div>

            @*<div class="field">
            @Html.LabelFor(m => m.TaskViewModel.TaskDate, new {@class = "label"})
            <div class="control">
                @Html.EditorFor(m => m.TaskViewModel.TaskDate, new { htmlAttributes = new { @class = "input" }, })
            </div>
            @Html.ValidationMessageFor(m => m.TaskViewModel.TaskDate)
        </div>*@

            @Html.HiddenFor(m => m.TaskViewModel.TaskDate)

            <!-- Form actions -->
            <div class="field is-grouped">
                <p class="control">
                    <input type="submit" name="Submit" value="Update" class="button is-primary" />
                </p>
                <p class="control">
                    <a class="button" href="@taskRepositoryPageUrl">
                        Cancel
                    </a>
                </p>
            </div>
        </div>
    </div>
}

CompanyHouseTest/CompanyHouseTest/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "_MasterView.cshtml";
}

CompanyHouseTest/CompanyHouseTest/Views/_MasterView.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

@* the fun starts here *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@Umbraco.Field("address")</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>

<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            COMPANY HOUSE | 31 E - Sommervej
        </a>


    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            @{
                var selection = Model.Content.Site().Children().Where(x => x.IsVisible());
            }
            @foreach (var item in selection)
            {
                <a class="@(item.IsAncestorOrSelf(Model.Content) ? "is-active" : "") navbar-item" href="@item.Url">
                    @item.Name</a>
            }

        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                @if (User.Identity.IsAuthenticated)
                {
                    <span>Welcome @User.Identity.Name</span>
                    <a class="button is-primary" href="~/Login">Logout</a>
                }
                else
                {
                    <a class="button is-primary" href="~/Login">Login</a>
                }
            </div>
        </div>
    </div>
</nav>


<section class="section">
    <div class="container">
        @RenderBody()
    </div>
</section>

<footer class="footer">
    <div class="content has-text-centered">
        <p>
            <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
            <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
            is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </p>
    </div>
</footer>


</body>
</html>